# Generated by Django 4.0.4 on 2022-06-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_obra_tecnica_remove_vehiculo_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='nombre de user')),
                ('password', models.CharField(max_length=10, verbose_name='contraseña de user')),
            ],
        ),
    ]
