# Generated by Django 4.0.4 on 2022-06-06 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='obra',
            fields=[
                ('idobra', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de obra')),
                ('autor', models.CharField(max_length=6, verbose_name='autor')),
                ('nombre', models.CharField(max_length=20, verbose_name='nombre obra')),
                ('descripcion', models.CharField(blank=True, max_length=20, null=True, verbose_name='descripcion obra')),
                ('precio', models.CharField(blank=True, max_length=20, null=True, verbose_name='precio de la obra')),
                ('imagen', models.CharField(blank=True, max_length=100, null=True, verbose_name='imagen de la obra')),
            ],
        ),
        migrations.CreateModel(
            name='tecnica',
            fields=[
                ('idtecnica', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de tecnica')),
                ('nombretecnica', models.CharField(max_length=50, verbose_name='Nombre del tecnica')),
            ],
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Vehiculo',
        ),
        migrations.AddField(
            model_name='obra',
            name='nombretecnica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tecnica'),
        ),
    ]
